customhost = "zitingdatabase.cwlz1pcb04nw.us-east-1.rds.amazonaws.com"
customuser = "ziting"
custompass = "ziting112233"
customdb = "employee"
custombucket = "zitingbucket"
customregion = "us-east-1"
AWS_ACCESS_KEY_ID = "ASIA2SH4QIYFEWTPUJCW"
AWS_SECRET_ACCESS_KEY = "1REkmnhADMF1G/ESofFoevHfU+/4SoJG0lIKqngH"
AWS_SESSION_TOKEN = "FwoGZXIvYXdzELD//////////wEaDHCKdoeXGwc2Bd3ZpyLPAWBANQi71A3OOMn8PiatPyWdoXrm9k901zEVt7CbssyzgAIqci9lNtkZqpSNWVFZu/K4CBk9W9p5o+kYCH6F+isAvGAd8fyOo9qUjUKrjSdO8h3j3AZSjIPcX3qkx76kZT9LZKrpU1QtLuGwGQngu7fn/unL4Wm8c/sOE/qNILO2zVzA5bHOmwQvmLZpPmgwEMg0FI7X9FbTRJzw9lI4GmSXrvscTZ+gaVUH6vaGOWEzp9qLVNqlOCwWOFcIYaedQAazPFolvJH+ke/cOih7jSiFj9qZBjItZHTyq4o5jtGxqf9cCrptDiwNyWiI4sE+0vEyKiHcjQ0xv5omzYYbKkvNbG1a"

